spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rs_system?characterEncoding=UTF-8
    username: root
    password: wyf19980715
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create